import * as fs from 'fs';
import * as path from 'path';
import { readEvents } from '../runtime';

interface EvolveOptions {
  apply?: boolean;
  fromPr?: string;
}

/**
 * `alp evolve` — Pillar 5 of V3: the Self-Evolving Protocol.
 *
 * Observes the runtime event log to detect patterns the swarm keeps
 * tripping over, then proposes concrete improvements to the workspace:
 *
 *  - Tasks/workflows that repeatedly fail (`[!]`) become candidate
 *    `@rule` blocks (a safety check the swarm should have followed).
 *  - Human handoffs (`[?]`) that recur on the same task hint at missing
 *    context and are surfaced for the maintainer.
 *
 * By default this is a *proposal* engine (dry, human-in-the-loop). Pass
 * `--apply` to write the proposed rules into `.alp/evolved.alp`.
 */
export function evolveCommand(options?: EvolveOptions) {
  const cwd = process.cwd();
  const alpDir = path.resolve(cwd, '.alp');
  if (!fs.existsSync(alpDir)) {
    console.error('Error: .alp directory not found. Run `alp init` first.');
    process.exit(1);
  }

  const events = readEvents(alpDir);
  if (events.length === 0) {
    console.log('No runtime events found yet. Run the swarm (`alp run --concurrent N`) first.');
    return;
  }

  // ─── 1. Failure telemetry ─────────────────────────────────────────────
  const failCount: Record<string, number> = {};
  const handoffCount: Record<string, number> = {};

  for (const e of events) {
    const id = e.task_id as string | undefined;
    if (!id) continue;
    if (e.type === 'task_status' && e.status === '[!]') {
      failCount[id] = (failCount[id] || 0) + 1;
    }
    if (e.type === 'workflow_fail') {
      failCount[id] = (failCount[id] || 0) + 1;
    }
    if (e.type === 'human_handoff' || e.status === '[?]') {
      handoffCount[id] = (handoffCount[id] || 0) + 1;
    }
  }

  const chronicFailures = Object.entries(failCount)
    .filter(([, n]) => n >= 2)
    .sort((a, b) => b[1] - a[1]);
  const chronicHandoffs = Object.entries(handoffCount)
    .filter(([, n]) => n >= 2)
    .sort((a, b) => b[1] - a[1]);

  console.log('\n🧬 ALP Self-Evolution Report\n');
  console.log(`   Analyzed ${events.length} runtime events.\n`);

  if (chronicFailures.length === 0 && chronicHandoffs.length === 0) {
    console.log('   ✅ No recurring failure patterns detected. The swarm is healthy.\n');
    return;
  }

  const proposedRules: string[] = [];

  if (chronicFailures.length > 0) {
    console.log('   ⚠️  Recurring failures (candidates for new @rule safety checks):');
    for (const [id, n] of chronicFailures) {
      console.log(`      • ${id} failed ${n}× — proposing a pre-flight verification rule.`);
      proposedRules.push(
        [
          `@rule`,
          `  id: rule-guard-${sanitize(id)}`,
          `  type: verification`,
          `  description: "Auto-extracted by alp evolve: task '${id}' failed ${n} times."`,
          `  condition: "Before marking '${id}' as done"`,
          `  action: "Run and pass all verification scripts for '${id}' before completion."`,
          `  severity: warning`,
        ].join('\n'),
      );
    }
    console.log('');
  }

  if (chronicHandoffs.length > 0) {
    console.log('   🙋 Recurring human handoffs (missing context — review these tasks):');
    for (const [id, n] of chronicHandoffs) {
      console.log(`      • ${id} escalated to a human ${n}× — likely under-specified.`);
    }
    console.log('');
  }

  if (options?.fromPr) {
    console.log(
      `   ℹ️  --from-pr ${options.fromPr}: PR-comment rule extraction requires a configured\n` +
        `      LLM provider and network access. Skipping automated extraction in this run.\n`,
    );
  }

  // ─── 2. Apply (optional) ──────────────────────────────────────────────
  if (options?.apply && proposedRules.length > 0) {
    const outPath = path.join(alpDir, 'evolved.alp');
    const header =
      `// Auto-generated by \`alp evolve\` on ${new Date().toISOString()}\n` +
      `// Review these proposed rules before committing them.\n\n`;
    fs.writeFileSync(outPath, header + proposedRules.join('\n\n') + '\n', 'utf-8');
    console.log(`   💾 Wrote ${proposedRules.length} proposed rule(s) to ${path.relative(cwd, outPath)}\n`);
  } else if (proposedRules.length > 0) {
    console.log('   Run `alp evolve --apply` to write these proposals to .alp/evolved.alp\n');
  }
}

function sanitize(id: string): string {
  return id.replace(/[^a-z0-9]+/gi, '-').replace(/^-+|-+$/g, '').toLowerCase();
}
