// AUTO-GENERATED. DO NOT EDIT.
module.exports = {
  "agent": require("./agent.schema.json"),
  "artifact": require("./artifact.schema.json"),
  "common": require("./common.schema.json"),
  "constraint": require("./constraint.schema.json"),
  "context": require("./context.schema.json"),
  "decision": require("./decision.schema.json"),
  "dependency": require("./dependency.schema.json"),
  "event": require("./event.schema.json"),
  "feature": require("./feature.schema.json"),
  "goal": require("./goal.schema.json"),
  "macro": require("./macro.schema.json"),
  "memory": require("./memory.schema.json"),
  "plugin": require("./plugin.schema.json"),
  "policy": require("./policy.schema.json"),
  "project": require("./project.schema.json"),
  "resource": require("./resource.schema.json"),
  "rule": require("./rule.schema.json"),
  "state": require("./state.schema.json"),
  "swarm": require("./swarm.schema.json"),
  "repo": require("./repo.schema.json"),
  "package": require("./package.schema.json"),
  "task": require("./task.schema.json"),
  "type": require("./type.schema.json"),
  "type_definition": require("./type_definition.schema.json"),
  "verification": require("./verification.schema.json"),
  "workflow": require("./workflow.schema.json"),
  "workspace": require("./workspace.schema.json"),
};
